### ISSUE TITLE
missing param.prototxt

### ISSUE THREAD

**Issue by ceccocats** [hitdshu/hityavie#1]
Hi,
Im testing this VIO method, can you provide your param.prototxt?
What dataset are you using?

Thanks,
Francesco

**Comment by hitdshu** [comment]
Hi Francesco,

Thanks for your interest.  I'm afraid I've lost the "param.prototxt" since I use a new laptop now and some data in my old laptop may be missing now...

I use the UZH_FPV2019 data for prototyping this method. See https://github.com/uzh-rpg/IROS2019-FPV-VIO-Competition . And maybe you could reproduce the param.prototxt from that data(This should be a big challenge). And may I suggest you to use other vio systems like Open_VINS/BASALT/VINS-MONO,...etc. 

Good luck,
Deshun

**Comment by ceccocats** [comment]
Thank you,
I like yours because is small and simple to understand, I already adapted your code to read my dataset but the prototxt is full of parameters that i have to try; maybe I will just use it as a tutorial.
The code does not have a license, is it free?

**Comment by hitdshu** [comment]
> Thank you,
> I like yours because is small and simple to understand, I already adapted your code to read my dataset but the prototxt is full of parameters that i have to try; maybe I will just use it as a tutorial.
> The code does not have a license, is it free?

No license. Absolutely free. And you can use it or modify it as you like.

**Comment by ceccocats** [comment]
Hi,
Im tryng to test with on the suggest dataset but the result is not good:
![Screenshot from 2020-07-01 13-05-46](https://user-images.githubusercontent.com/11562617/86237453-1469ed00-bb9c-11ea-8b54-4dcd86fd69f4.png)

This is my configuration file:
https://github.com/ceccocats/hityavie/blob/master/proto/param.prototxt
can you please check it? 

Also I often get this error with different number of features (ex 200):
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0701 13:11:17.967087  3661 problem_impl.cc:671] Parameter block not found: 0x3567bd8. You must add the parameter block to the problem before you can set its local parameterization.
*** Check failure stack trace: ***
Aborted
```
Any hints?

Thank you very much

**Comment by hitdshu** [comment]
> Hi,
> Im tryng to test with on the suggest dataset but the result is not good:
> ![Screenshot from 2020-07-01 13-05-46](https://user-images.githubusercontent.com/11562617/86237453-1469ed00-bb9c-11ea-8b54-4dcd86fd69f4.png)
> 
> This is my configuration file:
> https://github.com/ceccocats/hityavie/blob/master/proto/param.prototxt
> can you please check it?
> 
> Also I often get this error with different number of features (ex 200):
> 
> ```
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> F0701 13:11:17.967087  3661 problem_impl.cc:671] Parameter block not found: 0x3567bd8. You must add the parameter block to the problem before you can set its local parameterization.
> *** Check failure stack trace: ***
> Aborted
> ```
> 
> Any hints?
> 
> Thank you very much

Thanks for your interest and work. It's my pleasure to check the error and relating settings. Since I don't have much spare time on workdays, I'll try to debug it on this weekend. Let's hope we can solve this problem.

Deshun

**Comment by hitdshu** [comment]
![Screenshot from 2020-07-05 08-00-20](https://user-images.githubusercontent.com/52947865/86536487-8cc50b00-bf1a-11ea-8688-dde6ecf82745.png)
It seems I can't download the dataset....

**Comment by ceccocats** [comment]
Try this:
https://cloud.hipert.unimore.it/s/j348bSpZHWNZ8XN

**Comment by hitdshu** [comment]
Thanks. I downloaded it and use it for the program. The result is terrible. I think it might be the wrong variance config of the imu related noise.  
![Screenshot from 2020-07-06 08-42-57](https://user-images.githubusercontent.com/52947865/86612461-be090e00-bfe2-11ea-898a-6b757dfb70d7.png)
----Your imu noise setting
np {
    acc_noise: 0.1;
    gyr_noise: 0.05;
    ba_noise: 0.5;
    bg_noise: 0.5;
}
----
We might check this link for some information https://github.com/ethz-asl/kalibr/wiki/IMU-Noise-Model

Since it's late now, I have to stop debugging and go to bed. And I'll continue to debug the program tomorrow.

Deshun

**Comment by ceccocats** [comment]
Thank you!
I used this calibration file from the dataset providers for the IMU:
[results-imucam-..indoor_forward_calib_davis_imu.txt](https://github.com/hitdshu/hityavie/files/4880181/results-imucam-.indoor_forward_calib_davis_imu.txt)
Downloadable from(end of page): http://rpg.ifi.uzh.ch/uzh-fpv.html

ba_noise and bg_noise is completely random I dont know what is their meaning

Also, from the calib file gravity should be "-9.30066998"

**Comment by ceccocats** [comment]
I achived better results
![Screenshot from 2020-07-17 18-03-04](https://user-images.githubusercontent.com/11562617/87807016-08e31b00-c858-11ea-9dc6-d6cfb482330d.png)
The first lap is almost good, but the sencond fail:
![Screenshot from 2020-07-17 18-03-20](https://user-images.githubusercontent.com/11562617/87807098-21ebcc00-c858-11ea-8e6f-4ddb7d2fade6.png)

How I can debug this? Is it the Imu? is it the feature tracker? is it the optimization?
There are a lot of variables...

**Comment by hitdshu** [comment]
Well, that's impressive... Surely there are a lot of variables, and actually I've forgotten their true meaning too... I'm greatly surprised by your debugging result since this project seems like a stranger to me now.

Thanks for your great work. I devote recent weeks to my another project https://github.com/hitdshu/hitnlls, so I didn't spend much time debugging your problem..., sorry and hope you won't get disappointed. 

I didn't take serious attention to hityaive while writing them since I thought perhaps no one would use them... Now, perhaps I'm wrong and at least someone(perhaps only you) is using them...

And I'll start to rewrite hityavie project in a week or two, after finishing some unit tests and examples for hitnlls project.

**Comment by hitdshu** [comment]
By the way, feel free to modify the code. Since it doesn't have a license, you can use it as your code or everything else.

**Comment by ceccocats** [comment]
Thank you very much, also for me this is a side project I'm working on this in the spare time. I'm also looking at openvins.

> By the way, feel free to modify the code. Since it doesn't have a license, you can use it as your code or everything else.

Actually if it doesn't have a License all rights are yours by default, this is why I asked you some before. If you want to give free usage you should attach an open license like MIT.

**Comment by ceccocats** [comment]
It's funny because I'm also working at a solver. With the same interface of ceres-solver but completely on GPU

**Comment by hitdshu** [comment]
> Thank you very much, also for me this is a side project I'm working on this in the spare time. I'm also looking at openvins.
> 
> > By the way, feel free to modify the code. Since it doesn't have a license, you can use it as your code or everything else.
> 
> Actually if it doesn't have a License all rights are yours by default, this is why I asked you some before. If you want to give free usage you should attach an open license like MIT.

Ok. Now I've added a license https://github.com/hitdshu/hitnlls/blob/master/LICENSE, copyed from https://github.com/pjreddie/darknet/blob/master/LICENSE.fuck. Hahaha.

**Comment by hitdshu** [comment]
> It's funny because I'm also working at a solver. With the same interface of ceres-solver but completely on GPU

That's an interesting project. Looking forward to your solver.
